//
//  DemoStyleKit.swift
//  CMPopTipViewDemo-Swift
//
//  Created by Yichi Zhang on 13/12/2014.
//  Copyright (c) 2014 Yichi Zhang. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

import UIKit

public class DemoStyleKit : NSObject {
    
    //// Cache
    
    private struct Cache {
        static var imageOfOne: UIImage?
        static var oneTargets: [AnyObject]?
        static var imageOfTwo: UIImage?
        static var twoTargets: [AnyObject]?
        static var imageOfThree: UIImage?
        static var threeTargets: [AnyObject]?
        static var imageOfFour: UIImage?
        static var fourTargets: [AnyObject]?
    }
    
    //// Drawing Methods
    
    public class func drawOne() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Text Drawing
        let textRect = CGRectMake(0, 0, 25, 25)
        var textTextContent = NSString(string: "1")
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Center
        
        let textFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Bold", size: 25)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: textStyle]
        
        let textTextHeight: CGFloat = textTextContent.boundingRectWithSize(CGSizeMake(textRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect);
        textTextContent.drawInRect(CGRectMake(textRect.minX, textRect.minY + (textRect.height - textTextHeight) / 2, textRect.width, textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)
    }
    
    public class func drawTwo() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Text Drawing
        let textRect = CGRectMake(0, 0, 25, 25)
        var textTextContent = NSString(string: "2")
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Center
        
        let textFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Bold", size: 25)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: textStyle]
        
        let textTextHeight: CGFloat = textTextContent.boundingRectWithSize(CGSizeMake(textRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect);
        textTextContent.drawInRect(CGRectMake(textRect.minX, textRect.minY + (textRect.height - textTextHeight) / 2, textRect.width, textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)
    }
    
    public class func drawThree() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Text Drawing
        let textRect = CGRectMake(0, 0, 25, 25)
        var textTextContent = NSString(string: "3")
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Center
        
        let textFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Bold", size: 25)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: textStyle]
        
        let textTextHeight: CGFloat = textTextContent.boundingRectWithSize(CGSizeMake(textRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect);
        textTextContent.drawInRect(CGRectMake(textRect.minX, textRect.minY + (textRect.height - textTextHeight) / 2, textRect.width, textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)
    }
    
    public class func drawFour() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()
        
        //// Text Drawing
        let textRect = CGRectMake(0, 0, 25, 25)
        var textTextContent = NSString(string: "4")
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Center
        
        let textFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Bold", size: 25)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: textStyle]
        
        let textTextHeight: CGFloat = textTextContent.boundingRectWithSize(CGSizeMake(textRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect);
        textTextContent.drawInRect(CGRectMake(textRect.minX, textRect.minY + (textRect.height - textTextHeight) / 2, textRect.width, textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)
    }
    
    //// Generated Images
    
    public class var imageOfOne: UIImage {
        if Cache.imageOfOne != nil {
            return Cache.imageOfOne!
        }
        
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(25, 25), false, 0)
        DemoStyleKit.drawOne()
        
        Cache.imageOfOne = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        return Cache.imageOfOne!
    }
    
    public class var imageOfTwo: UIImage {
        if Cache.imageOfTwo != nil {
            return Cache.imageOfTwo!
        }
        
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(25, 25), false, 0)
        DemoStyleKit.drawTwo()
        
        Cache.imageOfTwo = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        return Cache.imageOfTwo!
    }
    
    public class var imageOfThree: UIImage {
        if Cache.imageOfThree != nil {
            return Cache.imageOfThree!
        }
        
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(25, 25), false, 0)
        DemoStyleKit.drawThree()
        
        Cache.imageOfThree = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        return Cache.imageOfThree!
    }
    
    public class var imageOfFour: UIImage {
        if Cache.imageOfFour != nil {
            return Cache.imageOfFour!
        }
        
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(25, 25), false, 0)
        DemoStyleKit.drawFour()
        
        Cache.imageOfFour = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        return Cache.imageOfFour!
    }
    
    //// Customization Infrastructure
    
    @IBOutlet var oneTargets: [AnyObject]! {
        get { return Cache.oneTargets }
        set {
            Cache.oneTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(DemoStyleKit.imageOfOne)
            }
        }
    }
    
    @IBOutlet var twoTargets: [AnyObject]! {
        get { return Cache.twoTargets }
        set {
            Cache.twoTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(DemoStyleKit.imageOfTwo)
            }
        }
    }
    
    @IBOutlet var threeTargets: [AnyObject]! {
        get { return Cache.threeTargets }
        set {
            Cache.threeTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(DemoStyleKit.imageOfThree)
            }
        }
    }
    
    @IBOutlet var fourTargets: [AnyObject]! {
        get { return Cache.fourTargets }
        set {
            Cache.fourTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(DemoStyleKit.imageOfFour)
            }
        }
    }
    
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
